services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client-app
    ports:
      - 80:80

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server-app
    restart: unless-stopped
    environment:
      - CORS="http://client:80"
    ports:
      - "4000:4000"